name: Deploy to production environment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    environment:
      name: production
      url: https://pdfparser.wrve.nl
    runs-on: ubuntu-latest
    steps:
      -   name: Deploy
          uses: appleboy/ssh-action@master
          env:
            SHA: ${{ github.sha }}
          with:
            host: ${{ secrets.host }}
            username: ${{ secrets.username }}
            password: ${{ secrets.password }}
            port: ${{ secrets.port }}
            envs: SHA
            script: |
              cd ${{ secrets.app_path }}
              php artisan down
              git fetch --all
              git checkout --force $SHA
              composer install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader
              php artisan config:cache
              php artisan route:cache
              php artisan view:cache
              php artisan up
              composer clear-cache
